# Generated by Django 5.1.1 on 2025-01-13 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
