# Generated by Django 5.1.1 on 2025-01-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_rename_create_at_chat_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='response',
            field=models.TextField(blank=True),
        ),
    ]
